In [1]:
import pandas as pd
import os
from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis as PA

In [2]:
df = pd.read_csv('data/CSVs/'+input("Enter File Name"))
#df = pd.read_csv('data/CSVs/filename.csv')
df

Enter File Name bacillus_anthracis.csv

,Unnamed: 0,sequence,length,IEP,MW,charge at pH 7
0,0,MENISDLWNSALKELEKKVSKPSYETWLKSTTAHNLKKDVLTITAP...,446,5.870127,50493.8525,-8.284830
1,1,MRFSIQKDYLVRSVQDVMKAVSFRTTIPILTGIKVVATEEGVTLTG...,379,5.199597,42649.6629,-11.907245
2,2,MKRIKISTEYITLGQFLKLADVIDTGGAVKWFLQEYEVYVNQELEN...,70,6.182229,8069.1211,-0.488451
3,3,MFISEIQLKNYRNYEKLELSFEDKVNVIIGENAQGKTNLMEAIYVL...,375,6.540088,43362.1786,-1.653395
4,4,MEQKQMQENSYDESQIQVLEGLEAVRKRPGMYIGSTSGKGLHHLVW...,640,6.016942,71895.5943,-8.903339
...,...,...,...,...,...,...
5306,5306,MEFDTIAAISTALGEGAIAIVRVSGDDAVEKVNRIFKGKDLTEVPS...,458,4.742214,50574.2320,-28.600898
5307,5307,MSIITAKGQTVELAVQDALRQLNVSKDRVDISIIDEGKRGFLGLFG...,205,9.602453,23120.4867,8.956833
5308,5308,MKKKLGLLAMVVALMAITAGCSEVNQPITPKSTGIWNEYFVYPLSQ...,255,9.590140,28423.7648,10.647947
5309,5309,MKKKHRIKKNDEFQTVFQKGKSNANRQFVVYQLDKEEQPNFRIGLS...,119,10.403086,14026.3450,17.670802
5310,5310,MKRTYQPNKRKRSKVHGFRSRMSTANGRKVLAARRRKGRKVLSA,44,11.999968,5170.0970,16.579437